/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DrivesRouteImport } from './routes/drives'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DrivesIndexRouteImport } from './routes/drives.index'
import { Route as DrivesDriveIdRouteImport } from './routes/drives.$driveId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesRoute = DrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesIndexRoute = DrivesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrivesRoute,
} as any)
const DrivesDriveIdRoute = DrivesDriveIdRouteImport.update({
  id: '/$driveId',
  path: '/$driveId',
  getParentRoute: () => DrivesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/drives': typeof DrivesRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/drives/$driveId': typeof DrivesDriveIdRoute
  '/drives/': typeof DrivesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/pipeline': typeof PipelineRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/drives/$driveId': typeof DrivesDriveIdRoute
  '/drives': typeof DrivesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/drives': typeof DrivesRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/drives/$driveId': typeof DrivesDriveIdRoute
  '/drives/': typeof DrivesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/drives'
    | '/pipeline'
    | '/prep'
    | '/profile'
    | '/drives/$driveId'
    | '/drives/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/pipeline'
    | '/prep'
    | '/profile'
    | '/drives/$driveId'
    | '/drives'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/drives'
    | '/pipeline'
    | '/prep'
    | '/profile'
    | '/drives/$driveId'
    | '/drives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DrivesRoute: typeof DrivesRouteWithChildren
  PipelineRoute: typeof PipelineRoute
  PrepRoute: typeof PrepRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives': {
      id: '/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof DrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives/': {
      id: '/drives/'
      path: '/'
      fullPath: '/drives/'
      preLoaderRoute: typeof DrivesIndexRouteImport
      parentRoute: typeof DrivesRoute
    }
    '/drives/$driveId': {
      id: '/drives/$driveId'
      path: '/$driveId'
      fullPath: '/drives/$driveId'
      preLoaderRoute: typeof DrivesDriveIdRouteImport
      parentRoute: typeof DrivesRoute
    }
  }
}

interface DrivesRouteChildren {
  DrivesDriveIdRoute: typeof DrivesDriveIdRoute
  DrivesIndexRoute: typeof DrivesIndexRoute
}

const DrivesRouteChildren: DrivesRouteChildren = {
  DrivesDriveIdRoute: DrivesDriveIdRoute,
  DrivesIndexRoute: DrivesIndexRoute,
}

const DrivesRouteWithChildren =
  DrivesRoute._addFileChildren(DrivesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DrivesRoute: DrivesRouteWithChildren,
  PipelineRoute: PipelineRoute,
  PrepRoute: PrepRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
